FROM node:lts

RUN apt-get update && apt-get install -y openssl
WORKDIR /app

COPY --chown=node:node package*.json ./
COPY prisma ./prisma/

RUN yarn

COPY --chown=node:node . .

# Reason to not use "RUN" command: https://notiz.dev/blog/prisma-migrate-deploy-with-docker
# RUN npx prisma generate

EXPOSE 3000
CMD ["yarn", "dev:migrate"]

